# version: 0.0
# Resources:
#   - TargetService:
#       Type: AWS::ECS::Service
#       Properties:
#         TaskDefinition: "arn:aws:ecs:us-east-1:522246528012:task-definition/dev-project-ecs-task:31"
#         LoadBalancerInfo:
#           ContainerName: dev-project-container-app
#           ContainerPort: 80





version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:111222333444:task-definition/my-task-definition-family-name:1"
        LoadBalancerInfo:
          ContainerName: "SampleApplicationName"
          ContainerPort: 80