#docker file to app simples hello world


# Use the official image as a parent image

FROM python:3.7-slim



WORKDIR /app

RUN apt update && apt install -y curl

RUN pip install flask

COPY . /app

ENTRYPOINT ["python" , "app.py"]